/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mate;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Magdalena
 */
public class FrmFormula extends javax.swing.JFrame {

    private int a;
    private int b;
    private int c;

    /**
     * Creates new form FrmFormula
     */
    public FrmFormula() {
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(458, 162);
        load();
    }

    private void load(){
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("fondo.jpg"));
        } catch (Exception e) {
        }
        Image dimg = img.getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lblFondo.setIcon(imageIcon);
    }
    
    private void calcular() {
        String resultado = "";
        a = Integer.parseInt(sA.getValue().toString());
        b = Integer.parseInt(sB.getValue().toString());
        c = Integer.parseInt(sC.getValue().toString());
        double determinante = Math.pow(b, 2) - (4 * a * c); //discriminante
        double eje = -b; //eje de simetría y vertice x
        eje /= (2 * a);
        double y = ((-determinante) / 4 * a); // vertice en y

        if (a < 0) {
            resultado += "Concava hacia arriba\n";
        } else {
            resultado += "Concava hacia abajo\n";
        }

        if (determinante >= 0) {
            resultado += "El discriminante es: " + determinante + "\n";
            double x1 = ((b * (-1)) + Math.sqrt(determinante)) / (2 * a);
            double x2 = ((b * (-1)) - Math.sqrt(determinante)) / (2 * a);
            resultado += "Cortes en X:  x1 = " + x1 + " x2= " + x2 + "\n";
            resultado += "Corte en el eje Y es= (0" + ","+c + ")\n";
            resultado += "Dominio = R\n";
            resultado += "Codominio = R\n";
            resultado += "Eje de simetría es: " + eje+ "\n";
            resultado += "El punto máximo es: (" + y + " , " + eje + ")\n";
            resultado += "Crece: [-∞, " + eje + "]\n";
            resultado += "Decrece: [" + eje +", " + "+∞]";
        }else{
            resultado += "El determinante es negativo y no se puede completar la operacion\n";
            resultado += "Pertenece a los números reales.";
        }
        this.setSize(458, 420);
        txtResultados.setText(resultado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sA = new javax.swing.JSpinner();
        sB = new javax.swing.JSpinner();
        sC = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        lblFondo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ecuación cuadratica");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 18, 431, 32);

        sA.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        sA.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(sA);
        sA.setBounds(121, 56, 62, 24);

        sB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        sB.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(sB);
        sB.setBounds(215, 56, 60, 24);

        sC.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        sC.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(sC);
        sC.setBounds(307, 56, 64, 24);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("a:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(107, 56, 10, 18);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("b:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(201, 59, 10, 18);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("c:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(293, 59, 10, 18);

        txtResultados.setEditable(false);
        txtResultados.setColumns(20);
        txtResultados.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtResultados.setRows(5);
        txtResultados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N
        jScrollPane1.setViewportView(txtResultados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 431, 236);
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 140, 450, 260);

        jPanel1.setBackground(new java.awt.Color(0, 0, 115));

        btnCalcular.setBackground(new java.awt.Color(0, 153, 255));
        btnCalcular.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 0, 115));
        btnCalcular.setText("Calcular");
        btnCalcular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 153, 255));
        btnLimpiar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 115));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        calcular();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtResultados.setText("");
        sA.setValue(0);
        sB.setValue(0);
        sC.setValue(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFormula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JSpinner sA;
    private javax.swing.JSpinner sB;
    private javax.swing.JSpinner sC;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
